@extends('admin.layouts.app')
@section('page-title','Website / Store Settings')
@section('content')
<form method="POST" action="{{ route('admin.settings.update') }}" enctype="multipart/form-data" class="grid gap-6 xl:grid-cols-3">@csrf @method('PUT')
    <section class="admin-card rounded-lg border border-slate-800 bg-slate-900 p-6"><h2 class="text-xl font-black text-white">General Settings</h2><label class="mt-4 block">Website Name<input name="website_name" value="{{ $settings['website_name'] ?? 'M&M Custom Tackle' }}" class="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"></label><label class="mt-4 block">Business Email<input name="business_email" value="{{ $settings['business_email'] ?? 'Mandmcustomtackle@gmail.com' }}" class="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"></label><label class="mt-4 block">Business Phone<input name="business_phone" value="{{ $settings['business_phone'] ?? '(941) 544-1066' }}" class="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"></label><label class="mt-4 block">Business Address<textarea name="business_address" rows="3" class="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2">{{ $settings['business_address'] ?? 'Sarasota, Florida' }}</textarea></label><label class="mt-4 block">Logo Upload<input name="logo" type="file" class="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"></label><label class="mt-4 block">Footer Text<textarea name="footer_text" rows="3" class="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2">{{ $settings['footer_text'] ?? '' }}</textarea></label></section>
    <section class="admin-card rounded-lg border border-slate-800 bg-slate-900 p-6"><h2 class="text-xl font-black text-white">Store Settings</h2><label class="mt-4 block">Currency<input name="currency" value="{{ $settings['currency'] ?? 'USD' }}" class="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"></label><label class="mt-4 block">Shipping Amount<input name="shipping_amount" type="number" step="0.01" value="{{ $settings['shipping_amount'] ?? '8.00' }}" class="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"></label><label class="mt-4 block">Tax Percentage<input name="tax_percentage" type="number" step="0.01" value="{{ $settings['tax_percentage'] ?? '0' }}" class="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"></label><label class="mt-4 block">Minimum Order Amount<input name="minimum_order_amount" type="number" step="0.01" value="{{ $settings['minimum_order_amount'] ?? '' }}" class="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"></label></section>
    <section class="admin-card rounded-lg border border-slate-800 bg-slate-900 p-6"><h2 class="text-xl font-black text-white">Website Content</h2><p class="mt-2 text-sm text-slate-400">TODO: Connect these settings to public page rendering where full CMS control is desired.</p><label class="mt-4 block">Home Hero Title<input name="home_hero_title" value="{{ $settings['home_hero_title'] ?? '' }}" class="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2"></label><label class="mt-4 block">Home Hero Subtitle<textarea name="home_hero_subtitle" rows="3" class="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2">{{ $settings['home_hero_subtitle'] ?? '' }}</textarea></label><label class="mt-4 block">About Page Content<textarea name="about_page_content" rows="4" class="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2">{{ $settings['about_page_content'] ?? '' }}</textarea></label><label class="mt-4 block">Contact Page Content<textarea name="contact_page_content" rows="4" class="mt-2 w-full rounded-lg border border-slate-700 bg-slate-950 px-3 py-2">{{ $settings['contact_page_content'] ?? '' }}</textarea></label></section>
    <div class="xl:col-span-3"><button class="rounded-lg bg-sky-500 px-6 py-3 font-bold text-slate-950">Save Settings</button></div>
</form>
@endsection
